# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newicwdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewIcwDialog(object):
    def setupUi(self, NewIcwDialog):
        NewIcwDialog.setObjectName("NewIcwDialog")
        NewIcwDialog.resize(418, 242)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        NewIcwDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewIcwDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(NewIcwDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.leProcId = QtWidgets.QLineEdit(self.frame)
        self.leProcId.setObjectName("leProcId")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leProcId)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.leIcw = QtWidgets.QLineEdit(self.frame)
        self.leIcw.setObjectName("leIcw")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leIcw)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.dsbMhr = QtWidgets.QDoubleSpinBox(self.frame)
        self.dsbMhr.setMaximum(10000.0)
        self.dsbMhr.setSingleStep(0.5)
        self.dsbMhr.setObjectName("dsbMhr")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dsbMhr)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.pltRemark = QtWidgets.QPlainTextEdit(self.frame)
        self.pltRemark.setObjectName("pltRemark")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pltRemark)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewIcwDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(NewIcwDialog)
        self.buttonBox.accepted.connect(NewIcwDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(NewIcwDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewIcwDialog)

    def retranslateUi(self, NewIcwDialog):
        _translate = QtCore.QCoreApplication.translate
        NewIcwDialog.setWindowTitle(_translate("NewIcwDialog", "New ICW"))
        self.label_3.setText(_translate("NewIcwDialog", "Procedure_ID:"))
        self.label_2.setText(_translate("NewIcwDialog", "ICW:"))
        self.label_4.setText(_translate("NewIcwDialog", "MHR:"))
        self.label_5.setText(_translate("NewIcwDialog", "Remark:"))
