# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newproclabeldialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewProcLabelDialog(object):
    def setupUi(self, NewProcLabelDialog):
        NewProcLabelDialog.setObjectName("NewProcLabelDialog")
        NewProcLabelDialog.resize(323, 72)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewProcLabelDialog.sizePolicy().hasHeightForWidth())
        NewProcLabelDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewProcLabelDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(NewProcLabelDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewProcLabelDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(NewProcLabelDialog)
        self.buttonBox.accepted.connect(NewProcLabelDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(NewProcLabelDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewProcLabelDialog)

    def retranslateUi(self, NewProcLabelDialog):
        _translate = QtCore.QCoreApplication.translate
        NewProcLabelDialog.setWindowTitle(_translate("NewProcLabelDialog", "New Label"))
        self.label.setText(_translate("NewProcLabelDialog", "Set Label:"))
