# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'texteditdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextEditDialog(object):
    def setupUi(self, TextEditDialog):
        TextEditDialog.setObjectName("TextEditDialog")
        TextEditDialog.resize(425, 246)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TextEditDialog.sizePolicy().hasHeightForWidth())
        TextEditDialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        TextEditDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(TextEditDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(TextEditDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.plainTextEdit)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(TextEditDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(TextEditDialog)
        self.buttonBox.accepted.connect(TextEditDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(TextEditDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TextEditDialog)

    def retranslateUi(self, TextEditDialog):
        _translate = QtCore.QCoreApplication.translate
        TextEditDialog.setWindowTitle(_translate("TextEditDialog", "Dialog"))
